name: Dependency Scan
on:
  merge_group: # Triggered when commits are added to merge queue
  pull_request: # Triggered when PR is submitted/updated
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  code-security: # "Dependency Review"
    uses: hellodigit/infra-tools/.github/workflows/reusable-dependency-review.yml@fc646d635ed27091760e9d07fbdce16d4294c41b # v1.204.5
